- name: Setup Kube Proxy
  hosts: proxy-servers
  become: yes
  tasks:
    - name: Update and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist
        force_apt_get: yes

    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present

    - name: Install python3-kubernetes
      apt:
        name: python3-kubernetes
        state: present

    - name: Download the latest kubectl binary
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      args:
        chdir: /tmp

    - name: Download the checksum for kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
      args:
        chdir: /tmp

    - name: Verify kubectl checksum
      shell: |
        echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
      args:
        chdir: /tmp

    - name: Install kubectl
      shell: |
        sudo install -o root -g root -m 0755 /tmp/kubectl /usr/local/bin/kubectl

    - name: Validate kubectl installation
      shell: kubectl version --client
      register: kubectl_version_output

    - name: Show kubectl version
      debug:
        msg: "{{ kubectl_version_output.stdout }}"
