---
- name: Copy SSH public key to all hosts
  hosts: all
  become: yes
  vars:
    ssh_pub_key_path: "{{ user_home }}/.ssh/id_rsa.pub"  # Path to the public key on the Ansible control machine

  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: "{{ user_home }}/.ssh"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0700'

    - name: Copy public key to authorized_keys
      authorized_key:
        user: "{{ user }}"
        state: present
        key: "{{ lookup('file', ssh_pub_key_path) }}"  # Reads the public key file

    - name: Ensure correct permissions for authorized_keys
      file:
        path: "{{ user_home }}/.ssh/authorized_keys"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0600'
